@ECHO OFF
SET DIR_PATH=%~dp0
SET DIR_PATH=%DIR_PATH:~0,-1%
SET USER_NAME=%1
SET USER_PASSWORD=%2
SET CHANGE_LOG_PATH=AuthDbChangeLog.yml
SET DB_NAME=AuthDb

CALL %DIR_PATH%\Update.bat %USER_NAME% %USER_PASSWORD% %DB_NAME% %CHANGE_LOG_PATH%